### ISSUE TITLE
1.21 please

### ISSUE THREAD

**Issue by kitovoi111** [EngineHub/WorldEditCUI#116]
### The Problem

1.21 please

### A Solution

1.21 please

**Comment by me4502** [comment]
see https://github.com/EngineHub/WorldEditCUI/pull/109#issuecomment-2175388284

**Comment by BrainStone** [comment]
I just want to quickly mention that using the `mc/1.21` branch you can build it yourself and if you want 1.21.1 support change these two lines in the `gradle/libs.versions.toml`

```toml
minecraft = "1.21.1"
fabricApi = "0.103.0+1.21.1"
```
